# Generated by Django 5.2.12 on 2026-04-03 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='time_scale',
        ),
    ]
