# Generated by Django 5.2.12 on 2026-04-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simulator", "0008_config_normal_user_rpm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simuser",
            name="mode",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("bursty", "Bursty"),
                    ("spammer", "Spammer"),
                ],
                default="normal",
                max_length=10,
            ),
        ),
    ]
