# Generated by Django 5.2.12 on 2026-04-07 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0009_alter_simuser_mode'),
        ('simulator', '0009_simuser_spend'),
    ]

    operations = [
    ]
